### ISSUE TITLE
gem naming issue

### ISSUE THREAD

**Issue by vikram-chaitanya** [sfaxon/has_features#1]
Hi,

I am writing a gem to add features to a model. The features are like subscription plan features. I plan to name the gem as has_features. Since you mentioned that the name for your gem was terrible, can you please consider changing the name to something else, at least the gem name.

i know its not something nice to ask you to change the name, but i have been trying to come up with some other name and couldn't figure out a better one.

Thanks,
Vikram

**Comment by sfaxon** [comment]
I'll send you an email about the possibility of transitioning the name. My concern is that projects using the currently released gem would break without any way to notify people using the gem.
